ss = {}
function ss.randomizeText(par)
  local phrases = 
    {
      'apeirophobia aaa so scary',
      'Snowbank Scripts',
      'doomer',
      'hi quexiol',
      'abc for a hot mom',
      'большой вонючий пердеж',
      'scary backrooms game',
      'im peeing my diaper',
      'rizzed up',
      'monkeysquad',
      '❄️❄️❄️',
      'Fuck tyrone',
      'give me admin plz',
      'give me staff plz',
      'give me mod plz', 
      '#UNBAN DOOM FROM MONOCHROME STUDIOS',
      'bruh',
      'Dicksonner',
      'you like men',
      'poop',
      'If theres a hole theres a goal',
      'Spy ZAPPIN my sentry',
      'BOTTOM TEXT',
      'my link diconnected',
      'you have executed this script now you are fucking gay and cant do shit',
      'Your mom',
      'i forgot to dispose of my feces',
      'tickletipson please no',
      'cum',
      'Th- th- the d-dog wa- wa-was ru- ru- running',
      'i have uncontrollable bowel movements',
      'You have executed this script, so now go beat the damn game',
      'shit up',
      'shit up hoe',
      'I executeed the scrip but i wanna execute you in bed',
      'My dog stepped on a bee',
      'shit the fuck up',
      'i love femboys',
      'shit the fick ip',
      'femboys >',
      'i nutted to cupid queen r34 and got magu and wings at the same time',
      'Pick up your Mcdonalds favorites fast when you link your credit or debit card for contactless payment in the app.',
      'Apeiroshitbia',
      'this gui makes me nut',
      'Execute this script and go kill them furries',
      'Im here to talk about your car’s extended warranty',
      'racially motiaved?',
      'You have executed this script, you are now tasked to annihilate all furries you see',
      'i will be very racist for $5 nitro',
      'no 🗿 🚬',
      'shit up retar',
      'put random sentences here for me to put in the gui',
      'BROOOO NO WAY I FEEL BNA',
      'i am getting my very racist words ready',
      'my friend doo doonig gumberry call of poo poo the 9th jackson stole my car and ran over a grandma',
      'shit up retar',
      'cock shit cum balls i nut to null',
      'null fucked my brother',
      'Humans do be cutting trees down and make the into a paper or a tissue then deadass said save the trees',
      'elon musk',
      '@Defector "Kyzer"',
      'mister pussy eater',
      'Cum balls',
      'Anogus',
      '???',
      'anigas',
      'YOU SHOULD GIVE ME STAFF... NOW!',
      'discord automod shart',
      'sexous',
      'I agree',
      'im about to get racist',
      'NULL NUTTED IN MY BROTHER',
      'oh no apeirophobia so scary!1!1!',
      'someone tell null to stop nutting in my brother',
      'SHUT UP KYZER',
      'POST IT AGAIN ITS SOOOO AWESOME',
      'ayo not this again',
      '68.72.32.192',
      'Kia — Today at 7:36 PM',
      '5',
      'worship cheese',
      'i know you like to watch rape hentai',
      'Your IP: 69.42.01.234',
      'general grant',
      'general lee',
      'pee and poo',
      'fart fart',
      '*farts cutely*',
      'yummy shartS',
  }

  wait(5)
  while true do
    wait(1)
    if par:IsA('TextLabel') then
    par.Text = phrases[math.random(1, #phrases)] end
  end
end
